name: Graybox Repo Sync

on:
  push:
    branches:
      - stage
      - main
  workflow_dispatch:
    inputs:
      syncBranch:
        description: 'Branch to sync'
        required: true
        default: 'stage'
        type: choice
        options:
          - 'stage'
          - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.FG_SYNC_APP_ID }}
          private-key: ${{ secrets.FG_SYNC_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "dc-graybox"

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.syncBranch || github.ref_name }}

      - name: Clone Graybox Repository and Checkout Selected Branch
        run: |
          git clone https://github.com/adobecom/dc-graybox.git ../dc-graybox
          cd ../dc-graybox
          git checkout $GB_SYNC_BRANCH
          echo "dc-graybox branch"
          git branch
          cd ../dc
          echo "dc branch"
          git branch
        env:
          GB_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}

      - name: Overwrite graybox repo files with latest from source repo
        run: |
          rsync -av --exclude='fstab.yaml' --exclude='.github'  --exclude='.kodiak' --exclude='.git' --exclude='.idea' --exclude='.husky' --exclude='.vscode' --exclude='tools/sidekick/config.json' ./ ../dc-graybox/

      - name: Commit and Push Changes to Graybox Repository
        run: |
          cd ../dc-graybox
          echo "dc-graybox branch"
          git branch
          git config user.email "$FG_SYNC_BOT_EMAIL"
          git config user.name "$FG_SYNC_BOT_NAME"
          git status
          if [[ -n $(git status -s) ]]; then
            git remote set-url origin https://oauth2:$GITHUB_TOKEN@github.com/adobecom/dc-graybox.git
            git remote -v
            git add .
            git commit -m "Syncing dc to dc-graybox"
            git push origin $GB_SYNC_BRANCH --force
            echo ":heavy_check_mark: Syncing branch $GB_SYNC_BRANCH on dc to dc-graybox completed successfully." >> $GITHUB_STEP_SUMMARY
          else
            echo ":heavy_minus_sign: No changes detected on branch $GB_SYNC_BRANCH, nothing to sync." >> $GITHUB_STEP_SUMMARY
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          FG_SYNC_BOT_EMAIL: ${{ secrets.FG_SYNC_BOT_EMAIL }}
          FG_SYNC_BOT_NAME: ${{ secrets.FG_SYNC_BOT_NAME }}
          GB_SYNC_BRANCH: ${{ inputs.syncBranch || github.ref_name }}
