name: Release

on:
  push:
    branches:
      - main
      - stage

jobs:
  clear-stage-cache:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/clear-cache.yml
    with:
      cpCode: 1551833
      network: production
    secrets: inherit

  clear-prod-cache:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/clear-cache.yml
    with:
      cpCode: 1551836
      network: production
    secrets: inherit
